language: node_js
node_js:
  - "4"
env:
  matrix:
    - UNDERSCORE=1.6 BACKBONE=1.1 MARIONETTE=2.2
    - UNDERSCORE=1.8 BACKBONE=1.1 MARIONETTE=2.3
    - UNDERSCORE=1.8 BACKBONE=1.3.2 MARIONETTE=2.4 MAINRUN=true
before_install:
  - npm config set ca ""
install:
  - curl -L https://rawgit.com/marionettejs/travis-ci-setup/master/ci.sh | bash
script: "gulp coverage"
after_success:
  - if [[ $MAINRUN == true ]]; then npm install -g codeclimate-test-reporter; fi
  - if [[ $MAINRUN == true ]]; then codeclimate-test-reporter < coverage/lcov.info
